server:
  port: 8761

spring:
  application:
    name: erueka-server


eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

